const initialMembers = [
  {
    id: 1,
    name: 'John',
    surname: 'Doe',
    age: 30,
    email: 'john@example.com',
    dateOfBirth: '1994-08-15',
    baptised: '2010-05-20',
    memberOf: 'Church A',
    localChurch: 'Local Church A',
    fromDate: '2010-05-20',
    father: 'Father Doe',
    mother: 'Mother Doe',
    image: 'https://via.placeholder.com/50',
  },
  {
    id: 2,
    name: 'Jane',
    surname: 'Smith',
    age: 28,
    email: 'jane@example.com',
    dateOfBirth: '1996-03-25',
    baptised: '2012-09-10',
    memberOf: 'Church B',
    localChurch: 'Local Church B',
    fromDate: '2012-09-10',
    father: 'Father Smith',
    mother: 'Mother Smith',
    image: 'https://via.placeholder.com/50',
  },
  {
    id: 3,
    name: 'Michael',
    surname: 'Johnson',
    age: 35,
    email: 'michael@example.com',
    dateOfBirth: '1989-11-12',
    baptised: '2008-07-05',
    memberOf: 'Church C',
    localChurch: 'Local Church C',
    fromDate: '2008-07-05',
    father: 'Father Johnson',
    mother: 'Mother Johnson',
    image: 'https://via.placeholder.com/50',
  },
  {
    id: 4,
    name: 'Emily',
    surname: 'Brown',
    age: 25,
    email: 'emily@example.com',
    dateOfBirth: '1999-05-03',
    baptised: '2015-12-18',
    memberOf: 'Church D',
    localChurch: 'Local Church D',
    fromDate: '2015-12-18',
    father: 'Father Brown',
    mother: 'Mother Brown',
    image: 'https://via.placeholder.com/50',
  },
  {
    id: 5,
    name: 'William',
    surname: 'Taylor',
    age: 40,
    email: 'william@example.com',
    dateOfBirth: '1984-09-20',
    baptised: '2005-10-30',
    memberOf: 'Church E',
    localChurch: 'Local Church E',
    fromDate: '2005-10-30',
    father: 'Father Taylor',
    mother: 'Mother Taylor',
    image: 'https://via.placeholder.com/50',
  },
];

